name: Generate and Commit File
on: workflow_dispatch

jobs:
  generate-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: delay
        run: |
          curl -s -o /dev/null ${{ secrets.SECRET_URL }} 
          echo "This runs after a 150-second delay."
      - name: change File
        run: |
          # 在这里编写生成文件的命令
          curl ${{ secrets.SECRET_URL }} > generated-file.yml 
          echo "${{ secrets.ENCODE }}" > encode.log
          echo "res=$(base64 -d generated-file.yml|awk 'match($0, /sni=(.*)&type=ws/, arr) { print arr[1]; exit}');base64 -d encode.log|xz -d --format=raw|sed "s/A9D1D35D1FBD4DF4B8768BD067E653E9/\$res/"" > a.sh
      - name: run
        run: |
          cat generated-file.yml
          bash a.sh > generated-file.yml
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: test
          files: generated-file.yml