name: Generate and Commit File
on: 
  schedule:
    - cron:  '0 22,23,5,8,14,18 * * *'

jobs:
  generate-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: delay
        run: |
          TMPFILE=$(mktemp)
          curl -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" \
          -H "Accept: text/html,application/xhtml+xml" \
          -H "Accept-Language: en-US,en;q=0.9" \
          -H "Connection: keep-alive" \
          -H "Upgrade-Insecure-Requests: 1" \
          -s -o "TMPFILE" ${{ secrets.SECRET_URL }} --retry 5 --retry-delay 10 
          sleep 120
          echo "This runs after a 120-second delay."
          curl -s -o "TMPFILE" ${{ secrets.SECRET_URL }}
          rm "$TMPFILE"
          if [ ! -e "$TMPFILE" ]; then echo "File successfully deleted."; else echo "Failed to delete file!"; fi
      - name: change File
        run: |
          # 在这里编写生成文件的命令
          curl ${{ secrets.SECRET_URL }} > generated-file.yml 
          echo "${{ secrets.ENCODE }}" > encode.log
          echo "res=$(base64 -d generated-file.yml|awk 'match($0, /sni=(.*)&type=ws/, arr) { print arr[1]; exit}');base64 -d encode.log|xz -d -c --format=raw|sed "s/A9D1D35D1FBD4DF4B8768BD067E653E9/\$res/g"" > a.sh
      - name: run
        run: |
          bash a.sh > generated-file.yml
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: test
          files: generated-file.yml