name: Generate and Commit File
on: 
  push:
    branches:
      - "test-workflow"

jobs:
  generate-and-commit-on-test-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: delay
        run: |
          TMPFILE=$(mktemp)
          curl -s -o "$TMPFILE" ${{ secrets.SECRET_URL }} --retry 5 --retry-delay 10
          rm "$TMPFILE"
          if [ ! -e "$TMPFILE" ]; then echo "File successfully deleted."; else echo "Failed to delete file!"; fi